CREATE TABLE IF NOT EXISTS chapters(
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  title TEXT NOT NULL,
  content TEXT,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  course_id INT NOT NULL,

  CONSTRAINT fk_course
    FOREIGN KEY(course_id)
      REFERENCES courses(id)
)
